Move to uniform disklabel handling with disktab
1. Gives us the ability to specify disk geometry to vnconfig, which is
the only way to use vnd with sector sizes other than 512bytes

2. Disklabel handling is now the same throughout all scripts which
need to create a label. vnconfig AND disklabel -w always
get all exact information in the exact same way. No more trying to
save old disklable information such as duids, what a stupid idea
that was.

The only disadvantage is that we need write access to the host
system /etc to be able to move the system disktab out of place
and put our temporary one in place. Although it's not ideal, it
is the only way to use disktab with the current libc implementation
short of chroot or other tricks that are not worth the effort.

diff --git a/growimg b/growimg
--- a/growimg
+++ b/growimg
@@ -24,6 +24,18 @@ uname=`uname -s`
 
 [ -z "$distloc" ] && distloc=/
 
+###
+#
+# disktab dance
+
+if [[ ! -w /etc ]]; then
+ echo "Can't do it, depends on disktab being replaceable!"
+ exit 1
+fi
+
+random=`dd if=/dev/urandom bs=512 count=1 2>/dev/null | sha512`
+tabname=`printf "%.8s" $random`
+
 vncfgroot() {
  c 0 vnconfig $rootdevice $1
 }
@@ -51,6 +63,7 @@ vnuncfgroot() {
 0() {
  rmdir $OldDir $NewDir
  rm -f $NewImg $NewLabel
+ [[ -f /etc/disktab.${tabname} ]] && mv /etc/disktab.${tabname} /etc/disktab
  exit 1
 }
 
@@ -138,7 +151,6 @@ if [ -z "$alt" ]; then
  cylinders=$((totalsize / 64))
  trackscylinder=1
  sectorstrack=64
- sectorscylinder=$((totalsize / cylinders))
 else
  # Here we use disklabel as a way to grab these values. OpenBSD 4.8+
  # always reports actual detected values (not what was stored on disk)
@@ -149,7 +161,6 @@ else
  totalsize=`awk -F: ' /^total sectors:/ {print $2} ' $tmplabel`
  bytessec=`awk -F: ' /^bytes\/sector:/ {print $2} ' $tmplabel`
  sectorstrack=`awk -F: ' /^sectors\/track:/ {print $2} ' $tmplabel`
- sectorscylinder=`awk -F: ' /^sectors\/cylinder:/ {print $2} ' $tmplabel`
  trackscylinder=`awk -F: ' /^tracks\/cylinder:/ {print $2} ' $tmplabel`
  cylinders=`awk -F: ' /^cylinders:/ {print $2} ' $tmplabel`
 
@@ -218,7 +229,7 @@ vncfgroot $image
 if [ -z "$alt" ]; then
  [ -z "$NewImg" ] && NewImg=$(c 0 mktemp -t growimg.XXXXXX)
 fi
-[ -z "$NewLabel" ] && NewLabel=$(c 0 mktemp -t growimg.XXXXXX)
+[ -z "$NewLabel" ] && NewLabel=$(c 0 mktemp -t growimg.disklabel.XXXXXX)
 [ -z "$OldDir" ] && OldDir=$(c 0 mktemp -t -d growimg.XXXXXX)
 [ -z "$NewDir" ] && NewDir=$(c 0 mktemp -t -d growimg.XXXXXX)
 
@@ -227,28 +238,20 @@ c 1 mount -o rdonly /dev/"$rootdevice"a $OldDir
 offset=64
 asize=$((totalsize - offset))
 
-# This probably isn't important as of OpenBSD 4.8 because disklabel
-# now ignores geometry specified by -R command.  Simply flashrd
-# as much as possible in this regard. XXX
-#
-c 2 cat > $NewLabel <<-EOF
-	type: ESDI
-	bytes/sector: $bytessec
-	sectors/track: $sectorstrack
-	tracks/cylinder: $trackscylinder
-	sectors/cylinder: $sectorscylinder
-	cylinders: $cylinders
-	total sectors: $totalsize
+echo "vnd-${tabname}:\\" > $NewLabel
+echo "	:dt=SCSI:ty=${tabname}:se#${bytessec}:nt#${trackscylinder}:ns#${sectorstrack}:nc#${cylinders}:su#${totalsize}:\\" >> $NewLabel
+echo "	:pa#${asize}:oa#${offset}:fa#$((bytessec * 2)):ba#$((bytessec * 16)):ta=4.2BSD:\\" >> $NewLabel
+echo "	:pc#${totalsize}:oc#0:" >> $NewLabel
 
-	a: $asize  $offset	4.2BSD  $((bytessec * 2))  $((bytessec * 16))  1
-	c: $totalsize 0 unused 0 0
-	EOF
+# DISKTAB MODIFIED
+c 2 mv /etc/disktab /etc/disktab.${tabname}
+c 2 cp $NewLabel /etc/disktab
 
 if [ -z "$alt" ]; then
  echo Creating new image...
  c 2 dd if=/dev/zero bs=512 count=512 of=$NewImg >/dev/null
 
- c 2 vnconfig $device $NewImg
+ c 2 vnconfig -t vnd-${tabname} $device $NewImg
  
  c 3 fdisk -l $totalsize -f /usr/mdec/mbr -yi $device
 else
@@ -257,7 +260,10 @@ fi
 
 echo
 echo Writing flashrd disklabel...
-c 3 disklabel -R $device $NewLabel
+c 3 disklabel -w $device vnd-${tabname}
+
+# DISKTAB ORIGINAL
+c 3 mv /etc/disktab.${tabname} /etc/disktab
 
 echo
 echo Creating new filesystem...
diff --git a/mkboot b/mkboot
--- a/mkboot
+++ b/mkboot
@@ -17,8 +17,20 @@ arch=`uname -m`
 
 [ -z "$dest" ] && dest=flashimg.$arch-$date
 
+###
+#
+# disktab dance
+
+if [[ ! -w /etc ]]; then
+ echo "Can't do it, depends on disktab being replaceable!"
+ exit 1
+fi
+
+random=`dd if=/dev/urandom bs=512 count=1 2>/dev/null | sha512`
+tabname=`printf "%.8s" $random`
+
 vncfgroot() {
- [[ $vnd == true ]] && c 0 vnconfig $rootdevice $1
+ [[ $vnd == true ]] && c 0 vnconfig -t vnd-${tabname} $rootdevice $1
 }
 
 vnuncfgroot() {
@@ -36,6 +48,7 @@ vnuncfgroot() {
  vnuncfgroot
 }
 0() {
+ [[ -f /etc/disktab.${tabname} ]] && mv /etc/disktab.${tabname} /etc/disktab
  exit 1
 }
 
@@ -52,14 +65,10 @@ tmplabel=$(c 0 mktemp -t mkbootlabel.XXXXXX)
 if [[ $vnd == true ]]; then
 
  # Create vnd image, must zero out the first few sectors or else disklabel freaks out...
- c 0 "dd if=/dev/zero bs=$bytessec count=$bytessec of=$dest > $TMPDIR/last.output 2>&1"
- vncfgroot $dest
+ c 0 "dd if=/dev/zero bs=512 count=512 of=$dest > $TMPDIR/last.output 2>&1"
  cylinders=$((totalsize / 64))
  trackscylinder=1
  sectorstrack=64
- c 1 "fdisk -l $totalsize -f $distloc/usr/mdec/mbr -yi $rootdevice > $TMPDIR/last.output 2>&1"
- c 1 disklabel $rootdevice > $tmplabel
- sectorscylinder=$((totalsize / cylinders))
 
 else
 
@@ -69,9 +78,9 @@ else
  totalsize=`awk -F: ' /^total sectors:/ {print $2} ' $tmplabel`
  bytessec=`awk -F: ' /^bytes\/sector:/ {print $2} ' $tmplabel`
  sectorstrack=`awk -F: ' /^sectors\/track:/ {print $2} ' $tmplabel`
- sectorscylinder=`awk -F: ' /^sectors\/cylinder:/ {print $2} ' $tmplabel`
  trackscylinder=`awk -F: ' /^tracks\/cylinder:/ {print $2} ' $tmplabel`
  cylinders=`awk -F: ' /^cylinders:/ {print $2} ' $tmplabel`
+
 fi
 
 totalmbytes=$((((totalsize / 1024) * bytessec) / 1024))
@@ -82,24 +91,28 @@ else
  echo ", $bytessec bytes/sector)"
 fi
 
-# Main partition comprises the total disk, minus first sector
+# Main partition comprises the total disk after offset
 offset=64
 asize=$((totalsize - offset))
 
-cat > $tmplabel <<-EOF
-	type: ESDI
-	bytes/sector: $bytessec
-	sectors/track: $sectorstrack
-	tracks/cylinder: $trackscylinder
-	sectors/cylinder: $sectorscylinder
-	cylinders: $cylinders
-	total sectors: $totalsize
+echo "vnd-${tabname}:\\" > $tmplabel
+echo "	:dt=SCSI:ty=${tabname}:se#${bytessec}:nt#${trackscylinder}:ns#${sectorstrack}:nc#${cylinders}:su#${totalsize}:\\" >> $tmplabel
+echo "	:pa#${asize}:oa#${offset}:fa#$((bytessec * 2)):ba#$((bytessec * 16)):ta=4.2BSD:\\" >> $tmplabel
+echo "	:pc#${totalsize}:oc#0:" >> $tmplabel
 
-	a: $asize   $offset   4.2BSD  $((bytessec * 2))  $((bytessec * 16))  1
-	c: $totalsize 0 unused 0 0
-	EOF
+# DISKTAB MODIFIED
+c 1 mv /etc/disktab /etc/disktab.${tabname}
+c 1 cp $tmplabel /etc/disktab
 
-c 1 disklabel -R $rootdevice $tmplabel
+if [[ $vnd == true ]]; then
+ vncfgroot $dest
+ c 1 "fdisk -l $totalsize -f $distloc/usr/mdec/mbr -yi $rootdevice > $TMPDIR/last.output 2>&1"
+fi
+
+c 1 "disklabel -w $rootdevice vnd-${tabname} > $TMPDIR/last.output 2>&1"
+
+# DISKTAB ORIGINAL
+c 1 mv /etc/disktab.${tabname} /etc/disktab
 
 echo -n Creating filesystem on /dev/r${rootdevice}a
 c 1 "newfs -S $bytessec /dev/r${rootdevice}a > $TMPDIR/last.output 2>&1"
diff --git a/mkdist b/mkdist
--- a/mkdist
+++ b/mkdist
@@ -78,6 +78,18 @@ fi
 
 ###
 #
+# disktab dance
+
+if [[ ! -w /etc ]]; then
+ echo "Can't do it, depends on disktab being replaceable!"
+ exit 1
+fi
+
+random=`dd if=/dev/urandom bs=512 count=1 2>/dev/null | sha512`
+tabname=`printf "%.8s" $random`
+
+###
+#
 # fall back
 
 2() {
@@ -87,6 +99,7 @@ fi
  vnconfig -u $device
 }
 0() {
+ [[ -f /etc/disktab.${tabname} ]] && mv /etc/disktab.${tabname} /etc/disktab
  exit 1
 }
 
@@ -142,28 +155,17 @@ echo -n "Size openbsd.vnd $((disktotal / 2048))MB "
 c 0 "dd if=/dev/zero of=$tmpmnt/openbsd.vnd bs=512 count=512 > $TMPDIR/last.output 2>&1"
 echo
 
-c 0 vnconfig $device $tmpmnt/openbsd.vnd
-
 bytessec=512
-sectorstrack=100
+sectorstrack=64
 trackscylinder=1
 cylinders=$((disktotal / sectorstrack))
-sectorscylinder=$((disktotal / cylinders))
-
-cat >> ${tmplabel} <<-EOF
-	bytes/sector: $bytessec
-	sectors/track: $sectorstrack
-	tracks/cylinder: $trackscylinder
-	sectors/cylinder: $sectorscylinder
-	cylinders: $cylinders
-	total sectors: $disktotal
-
-	c: $disktotal 0 unused 0 0
-	EOF
 
 ###
 #
-# Build, write vnd disklabel
+# Generate openbsd.vnd disktab
+
+echo "vnd-${tabname}:\\" > $tmplabel
+echo "	:dt=SCSI:ty=${tabname}:se#${bytessec}:nt#${trackscylinder}:ns#${sectorstrack}:nc#${cylinders}:su#${disktotal}:\\" >> $tmplabel
 
 x=0
 offset=64
@@ -171,13 +173,28 @@ offset=64
 
 for i in $vnddirs; do
 
- echo "${part[$x]}: ${total[$x]}  $offset   4.2BSD  $((bytessec * 2))   $((bytessec * 16))    1"  >> $tmplabel
+ e="${part[$x]}"
+
+ echo "	:p${e}#${total[$x]}:o${e}#${offset}:f${e}#$((bytessec * 2)):b${e}#$((bytessec * 16)):t${e}=4.2BSD:ty=${tabname}:\\" >> $tmplabel
 
  offset=$((offset+${total[$x]}))
  ((x++))
 done
 
-c 1 disklabel -R $device $tmplabel
+echo "	:pc#${disktotal}:oc#0:ty=${tabname}:" >> $tmplabel
+
+# DISKTAB MODIFIED
+c 0 mv /etc/disktab /etc/disktab.${tabname}
+
+c 0 cp $tmplabel /etc/disktab
+c 0 cp $tmplabel $TMPDIR/vnd.disktab
+
+c 0 vnconfig -t vnd-${tabname} $device $tmpmnt/openbsd.vnd
+
+c 1 "disklabel -w $device vnd-${tabname} > $TMPDIR/last.output 2>&1"
+
+# DISKTAB ORIGINAL
+c 1 mv /etc/disktab.${tabname} /etc/disktab
 
 ###
 #
diff --git a/mkrdroot b/mkrdroot
--- a/mkrdroot
+++ b/mkrdroot
@@ -49,6 +49,18 @@ fi
 
 ###
 #
+# disktab dance
+
+if [[ ! -w /etc ]]; then
+ echo "Can't do it, depends on disktab being replaceable!"
+ exit 1
+fi
+
+random=`dd if=/dev/urandom bs=512 count=1 2>/dev/null | sha512`
+tabname=`printf "%.8s" $random`
+
+###
+#
 # fall back
 
 2() {
@@ -58,6 +70,7 @@ fi
  vnconfig -u $device
 }
 0() {
+ [[ -f /etc/disktab.${tabname} ]] && mv /etc/disktab.${tabname} /etc/disktab
  exit 1
 }
 
@@ -87,19 +100,24 @@ echo Creating ramdisk rootfs
 
 c 0 "dd if=/dev/zero of=$rdroot bs=512 count=$blocks > $TMPDIR/last.output 2>&1"
 
-c 0 vnconfig $device $rdroot
-
 tmplabel=$(c 0 mktemp -t mkrdrootlabel.XXXXXX)
 tmpmntdir=$(c 0 mktemp -t -d mkrdroot.XXXXXX)
 
-c 1 "disklabel $device > $tmplabel 2> $TMPDIR/last.output"
+echo "vnd-${tabname}:\\" > $tmplabel
+echo "	:dt=SCSI:ty=${tabname}:se#512:nt#1:ns#64:nc#$((blocks / 64)):su#${blocks}:\\" >> $tmplabel
+echo "	:pa#${blocks}:oa#0:fa#1024:ba#8192:ta=4.2BSD:\\" >> $tmplabel
+echo "	:pc#${blocks}:oc#0:tc=unused:" >> $tmplabel
 
-totalsize=`awk -F: ' /^total sectors:/ {print $2} ' $tmplabel`
-cat >>$tmplabel <<-EOF
-	a: $totalsize   0   4.2BSD  1024    8192    1
-	EOF
+# DISKTAB MODIFIED
+c 0 mv /etc/disktab /etc/disktab.${tabname}
+c 0 cp $tmplabel /etc/disktab
 
-c 1 "disklabel -R $device $tmplabel > $TMPDIR/last.output 2>&1"
+c 0 vnconfig -t vnd-${tabname} $device $rdroot
+
+c 1 "disklabel -w $device vnd-${tabname} > $TMPDIR/last.output 2>&1"
+
+# DISKTAB ORIGINAL
+c 1 mv /etc/disktab.${tabname} /etc/disktab
 
 c 1 "newfs -m 0 -o space -i 1024 /dev/r${device}a > $TMPDIR/last.output 2>&1"
 
